---
#- name: download grafana GPG key
#  shell: |
#    set -o pipefail
#    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
#  args:
#   executable: /bin/bash
#
#- name: check if grafana.list file already exists
#  stat:
#    path: /etc/apt/sources.list.d/grafana.list
#  register: grafana_list_file
#
#- name: adding grafana repo
#  shell: |
#    set -o pipefail
#    echo "deb https://packages.grafana.com/enterprise/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list
#  args:
#    executable: /bin/bash
#  when: not grafana_list_file.stat.exists
#
#
- name: download grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: adding grafana repo
  blockinfile:
    create: yes
    path: /etc/apt/sources.list.d/grafana.list
    insertbefore: EOF
    block: |
      deb https://packages.grafana.com/enterprise/deb stable main

- name: install grafana-enterprise
  apt:
    name: grafana-enterprise
    state: present
    update_cache: yes

- name: start grafana service
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
