---
- name: create node_exporter download dir
  file:
    path: /root/node_exporter
    state: directory
    mode: '0755'

- name: get current node_exporter sha256
  shell: |
    sha256sum /root/node_exporter/archive.tar.gz | sed -n 's/^\(\S*\).*/sha256:\1/p'
  args:
    executable: /bin/bash
  register: node_exporter_sha256

- name: download node_exporter
  get_url:
    url: '{{ node_exporter_binary_url | quote }}'
    checksum: '{{ node_exporter_binary_checksum | quote }}'
    dest: /root/node_exporter/archive.tar.gz
    mode: '0700'
  when: node_exporter_sha256.stdout != node_exporter_binary_checksum

- name: unarchive node_exporter
  unarchive:
    src: /root/node_exporter/archive.tar.gz
    remote_src: yes
    dest: /root/node_exporter
  when: node_exporter_sha256.stdout != node_exporter_binary_checksum

- name: copy node_exporter binary
  shell: |
    set -o pipefail
    cp /root/node_exporter/node_exporter*linux-amd64/node_exporter /usr/local/bin/
    chmod 755 /usr/local/bin/node_exporter
    chown root:root /usr/local/bin/node_exporter
  args:
    executable: /bin/bash
  changed_when: False
  when: node_exporter_sha256.stdout != node_exporter_binary_checksum

- name: create node_exporter systemd unit
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '600'

- name: start node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
