---
- name: check if nginx-selfsigned SSL already exists
  stat:
    path: /etc/ssl/private/nginx-selfsigned.key
  register: nginx_selfsigned_ssl

- name: check if Diffie-Hellman file already exists
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: dhparam_pem

- name: generating selfsigned SSL pair
  shell: |
    set -o pipefail
    openssl req -x509 -nodes -days 1825 -addext "subjectAltName = IP:{{ ansible_default_ipv4.address }}"  -newkey rsa:4096 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=XX/ST=XX/L=XX/O=XX/OU=XX/CN=XX"
  args:
    executable: /bin/bash
  when: not nginx_selfsigned_ssl.stat.exists

- name: generating Diffie-Hellman file
  shell: |
    set -o pipefail
    openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  args:
    executable: /bin/bash
  when: not dhparam_pem.stat.exists
